defaults: &defaults
  working_directory: ~/repo
  docker:
      - image: circleci/node:10.10

version: 2
jobs:
  install_packages:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm test
  link:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm lint
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm run build
workflows:
  version: 2
  build_and_test:
    jobs:
      - install_packages
      - test:
          requires:
            - install_packages
      - lint:
          requires:
            - install_packages
      - build:
          requires:
            - test
            - lint


