# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  install_packages:
    docker:
      - image: circleci/node:10.10
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    docker:
      - image: circleci/node:10.10
    steps:
      - checkout
      - run: npm test
      - run: npm lint
  build:
    docker:
      - image: circleci/node:10.10
    steps:
      - checkout
      - run: npm run build
workflows:
  version: 2
  build_and_test:
    jobs:
      - install_packages
      - test:
          requires:
            - install_packages
      - build:
          requires:
            - install_packages


