defaults: &defaults
  working_directory: ~/repo
  docker:
      - image: circleci/node:10.10

persist: &persist
  paths:
    - dist/*
    - node_modules/*
    - src/*
    - package.json
    - webpack.config.js
    
version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/
          paths:
            - repo/*
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm test
  link:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm lint
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm run build
workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
      - lint:
          requires:
            - checkout
      - build:
          requires:
            - test
            - lint


