defaults: &defaults
  working_directory: ~/repo
  docker:
      - image: circleci/node:10.10

version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths: .
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm test
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm run lint
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths: .
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: 
          name: Deploy to github pages
          command: |
            cd dist
            git init
            
            git config --local user.email $GH_EMAIL
            git config --local user.name $GH_NAME
      
            git remote add deploy $CIRCLE_REPOSITORY_URL
            git add -A
            git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}"

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout:      
          filters:
            branches:
              ignore: gh-pages
      - test:
          requires:
            - checkout
      - lint:
          requires:
            - checkout
      - build:
          requires:
            - test
            - lint
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: 
                - master